Kan 3 contest creation page UI
monolit9951/contests-frontend pull request #26
Opened 2024-05-18 20:20 UTC by Yura-Kost

In this branch i was working with page for creating post constest request.

Here i added some extra svgs, created flexible combobox component, modified scss files for input files to use webkit for applying custom design, and created the design itself

2024-05-20 12:42 UTC, VolodymyrKholiavko commented on src/shared/ui/mainInfoRadioEl/ui/mainInfoRadioEl.tsx
> +        /* eslint-disable jsx-a11y/click-events-have-key-events */
comments should be removed or resolved

2024-05-20 13:18 UTC, VolodymyrKholiavko commented on src/widgets/galleryUpload/ui/galleryUpload.tsx
> +            <div className='grid_photo_container'>
should be mapped

2024-05-20 13:19 UTC, VolodymyrKholiavko commented on src/widgets/prizeInformation/ui/prizeInformation.tsx
> +                <PrizePlace winIcon={win1} deleteIcon={trash} />
should be mapped

2024-05-20 13:20 UTC, VolodymyrKholiavko requested changes
Good at all but still much incorrect architecture usages

2024-05-21 09:21 UTC, VolodymyrKholiavko requested changes
Done

2024-05-27 09:57 UTC, FreadSt commented on src/shared/ui/mainInfoRadioEl/ui/mainInfoRadioEl.tsx
> +        /* eslint-disable jsx-a11y/click-events-have-key-events */
by the way, "resolve" means dealing with the warnings eslint

2024-05-27 10:59 UTC, FreadSt commented on src/shared/ui/mainInfoRadioElContainer/ui/mainInfoRadioElContainer.tsx
> +        <VStack className='mainInfoRadioElContainer_container'>
should be renamed classname to shorter and understandable

2024-05-27 11:21 UTC, FreadSt commented on src/widgets/mainInformation/ui/mainInformation.tsx
> +const categories = [
mock constants should be moved to separate directories

2024-05-27 11:35 UTC, FreadSt requested changes
Done. Good at all but need more attention to architecture and naming

2024-05-29 08:53 UTC, FreadSt approved these changes

2024-05-29 09:00 UTC, FreadSt requested changes
done

2024-05-29 09:01 UTC, merged